# Generated by Django 5.1.1 on 2024-10-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci2biz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
