# Generated by Django 5.1.1 on 2024-10-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci2biz_app', '0004_rename_user_id_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
