# Generated by Django 5.1.1 on 2024-11-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci2biz_app', '0005_users_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('indicacao_ativa', models.BooleanField(default=True)),
                ('fluxo', models.TextField(null=True)),
                ('perspectiva', models.TextField(null=True)),
                ('orientacoes_pesquisa', models.TextField(null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
