# Generated by Django 5.1.1 on 2024-11-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci2biz_app', '0006_demanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='indicacao_ativa',
            field=models.BooleanField(default=False),
        ),
    ]
