# Generated by Django 5.1.1 on 2024-11-18 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci2biz_app', '0007_alter_demanda_indicacao_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='professor_responsavel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
