# Generated by Django 5.1.1 on 2024-12-02 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci2biz_app', '0008_demanda_professor_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('demanda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci2biz_app.demanda')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoTurmas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=5000)),
                ('lider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci2biz_app.turma')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci2biz_app.grupoturmas')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci2biz_app.turma')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
