# Generated by Django 5.1.1 on 2024-12-02 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci2biz_app', '0009_turma_grupoturmas_usuarioturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='monitor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_turmas', to=settings.AUTH_USER_MODEL),
        ),
    ]
