# Generated by Django 5.1.1 on 2024-12-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci2biz_app', '0010_turma_monitor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='monitor_id',
        ),
    ]
